language: java
install: true

jdk:
  - openjdk8

script:
  - git clone https://github.com/mernst/returnsrecv-checker.git
  - (cd returnsrecv-checker && ./gradlew build && ./gradlew publishToMavenLocal)
  - ./gradlew build --stacktrace
